# Width and Height of the project window
WINDOW_WIDTH = 360
WINDOW_HEIGHT = 720

POST_WIDTH = 0.87 * WINDOW_WIDTH
POST_HEIGHT = 0.41 * WINDOW_HEIGHT
POST_X_POS = 0.064 * WINDOW_WIDTH
POST_Y_POS = 0.2 * WINDOW_HEIGHT

LIKE_BUTTON_X_POS = 0.1 * WINDOW_WIDTH
LIKE_BUTTON_Y_POS = 0.622 * WINDOW_HEIGHT
LIKE_BUTTON_WIDTH = 0.067 * WINDOW_WIDTH
LIKE_BUTTON_HEIGHT = 0.033 * WINDOW_HEIGHT

COMMENT_BUTTON_X_POS = 0.195 * WINDOW_WIDTH
COMMENT_BUTTON_Y_POS = 0.622 * WINDOW_HEIGHT
COMMENT_BUTTON_WIDTH = 0.067 * WINDOW_WIDTH
COMMENT_BUTTON_HEIGHT = 0.033 * WINDOW_HEIGHT

SHARE_BUTTON_X_POS = 0.289 * WINDOW_WIDTH
SHARE_BUTTON_Y_POS = 0.622 * WINDOW_HEIGHT
SHARE_BUTTON_WIDTH = 0.067 * WINDOW_WIDTH
SHARE_BUTTON_HEIGHT = 0.033 * WINDOW_HEIGHT

TEXT_POST_FONT_SIZE = 40
LINE_MAX_LENGTH = 20

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)


